"""initial schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('snoozed_until', sa.Date(), nullable=True),
    sa.Column('comments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_model_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('device_category', sa.String(length=50), nullable=False),
    sa.Column('typical_age_years', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('expected_process_minutes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_first_pass_yield_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('expected_exception_rate_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('expected_repair_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_resale_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_sell_through_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('partner_type', sa.String(length=50), nullable=False),
    sa.Column('geography', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=False),
    sa.Column('expected_monthly_volume', sa.Integer(), nullable=True),
    sa.Column('data_security_requirement', sa.String(length=50), nullable=False),
    sa.Column('sourcing_method', sa.String(length=100), nullable=True),
    sa.Column('logistics_method', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('robot_cells',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cell_name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('standard_daily_capacity_units', sa.Integer(), nullable=True),
    sa.Column('standard_daily_capacity_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('supported_device_categories', sa.JSON(), nullable=True),
    sa.Column('supported_workflows', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cell_name')
    )
    op.create_table('capacity_calendar',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('robot_cell_id', sa.String(length=36), nullable=False),
    sa.Column('calendar_date', sa.Date(), nullable=False),
    sa.Column('scheduled_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('maintenance_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('downtime_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('assigned_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('available_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['robot_cell_id'], ['robot_cells.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('robot_cell_id', 'calendar_date')
    )
    op.create_table('partner_contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('contract_name', sa.String(length=255), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('inventory_ownership_model', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('acquisition_cost_per_unit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('service_fee_per_unit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('revenue_share_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('expected_monthly_volume', sa.Integer(), nullable=True),
    sa.Column('minimum_volume_commitment', sa.Integer(), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('document_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_cohorts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=True),
    sa.Column('cohort_code', sa.String(length=100), nullable=False),
    sa.Column('cohort_name', sa.String(length=255), nullable=False),
    sa.Column('intake_date', sa.Date(), nullable=True),
    sa.Column('expected_device_count', sa.Integer(), nullable=False),
    sa.Column('actual_device_count', sa.Integer(), nullable=False),
    sa.Column('ownership_model', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority_score', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('target_completion_date', sa.Date(), nullable=True),
    sa.Column('target_sale_date', sa.Date(), nullable=True),
    sa.Column('approved_budget_version_id', sa.String(length=36), nullable=True),
    sa.Column('margin_floor_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('decision_rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['partner_contracts.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cohort_code')
    )
    op.create_table('cohort_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('robot_cell_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('planned_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('planned_units', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('daily_plan', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['device_cohorts.id'], ),
    sa.ForeignKeyConstraint(['robot_cell_id'], ['robot_cells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cohort_budget_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('scenario_type', sa.String(length=30), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('expected_units_received', sa.Integer(), nullable=False),
    sa.Column('expected_units_processed', sa.Integer(), nullable=False),
    sa.Column('expected_units_sold', sa.Integer(), nullable=False),
    sa.Column('expected_acquisition_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_inbound_logistics_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_robot_hours', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_robot_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_manual_labor_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_repair_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_outbound_fulfillment_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_marketplace_fees', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_revenue', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_contribution_margin', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_cash_exposure', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_collection_days', sa.Integer(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('economics', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.JSON(), nullable=True),
    sa.Column('decision_rationale', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['device_cohorts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cohort_model_mix',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('device_model_profile_id', sa.String(length=36), nullable=False),
    sa.Column('expected_unit_count', sa.Integer(), nullable=False),
    sa.Column('expected_condition_grade', sa.String(length=20), nullable=True),
    sa.Column('expected_resale_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_process_minutes', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_exception_rate_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('expected_repair_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['device_cohorts.id'], ),
    sa.ForeignKeyConstraint(['device_model_profile_id'], ['device_model_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=True),
    sa.Column('partner_id', sa.String(length=36), nullable=True),
    sa.Column('robot_cell_id', sa.String(length=36), nullable=True),
    sa.Column('cost_date', sa.Date(), nullable=False),
    sa.Column('cost_category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_ref', sa.String(length=100), nullable=True),
    sa.Column('allocation_rule', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['device_cohorts.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.ForeignKeyConstraint(['robot_cell_id'], ['robot_cells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('robot_cell_id', sa.String(length=36), nullable=False),
    sa.Column('operation_date', sa.Date(), nullable=False),
    sa.Column('devices_received', sa.Integer(), nullable=False),
    sa.Column('devices_started', sa.Integer(), nullable=False),
    sa.Column('devices_completed', sa.Integer(), nullable=False),
    sa.Column('first_pass_completions', sa.Integer(), nullable=False),
    sa.Column('manual_exception_count', sa.Integer(), nullable=False),
    sa.Column('devices_under_repair', sa.Integer(), nullable=False),
    sa.Column('quality_approved_count', sa.Integer(), nullable=False),
    sa.Column('rework_events', sa.Integer(), nullable=False),
    sa.Column('productive_robot_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('downtime_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('downtime_reason', sa.String(length=255), nullable=True),
    sa.Column('technician_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('labor_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('repair_parts_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['device_cohorts.id'], ),
    sa.ForeignKeyConstraint(['robot_cell_id'], ['robot_cells.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cohort_id', 'robot_cell_id', 'operation_date')
    )
    op.create_table('exception_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('device_model_profile_id', sa.String(length=36), nullable=True),
    sa.Column('robot_cell_id', sa.String(length=36), nullable=True),
    sa.Column('exception_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=False),
    sa.Column('estimated_resolution_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('actual_resolution_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['device_cohorts.id'], ),
    sa.ForeignKeyConstraint(['device_model_profile_id'], ['device_model_profiles.id'], ),
    sa.ForeignKeyConstraint(['robot_cell_id'], ['robot_cells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=True),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['device_cohorts.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('resale_listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('listing_channel', sa.String(length=100), nullable=False),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('listing_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['device_cohorts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('resale_listing_id', sa.String(length=36), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('units_sold', sa.Integer(), nullable=False),
    sa.Column('units_returned', sa.Integer(), nullable=False),
    sa.Column('gross_sale_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('marketplace_fee', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('return_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('net_sale_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=30), nullable=False),
    sa.Column('payout_due_date', sa.Date(), nullable=True),
    sa.Column('payout_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['device_cohorts.id'], ),
    sa.ForeignKeyConstraint(['resale_listing_id'], ['resale_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_receipts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=True),
    sa.Column('sales_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('receipt_type', sa.String(length=50), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['sales_transaction_id'], ['sales_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cash_receipts')
    op.drop_table('sales_transactions')
    op.drop_table('resale_listings')
    op.drop_table('invoices')
    op.drop_table('exception_events')
    op.drop_table('daily_operations')
    op.drop_table('cost_entries')
    op.drop_table('cohort_model_mix')
    op.drop_table('cohort_budget_versions')
    op.drop_table('cohort_assignments')
    op.drop_table('device_cohorts')
    op.drop_table('partner_contracts')
    op.drop_table('capacity_calendar')
    op.drop_table('robot_cells')
    op.drop_table('policy_settings')
    op.drop_table('partners')
    op.drop_table('device_model_profiles')
    op.drop_table('audit_log')
    op.drop_table('alerts')
    # ### end Alembic commands ###
