"""device ledger and custody events

Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cohort_id', sa.String(length=36), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('asset_tag', sa.String(length=100), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('storage_type', sa.String(length=30), nullable=False),
    sa.Column('intake_condition_grade', sa.String(length=5), nullable=True),
    sa.Column('intake_timestamp', sa.DateTime(), nullable=False),
    sa.Column('current_location', sa.String(length=100), nullable=True),
    sa.Column('current_custodian', sa.String(length=100), nullable=True),
    sa.Column('current_status', sa.String(length=30), nullable=False),
    sa.Column('data_sanitization_required', sa.Boolean(), nullable=False),
    sa.Column('sanitization_method', sa.String(length=100), nullable=True),
    sa.Column('sanitization_status', sa.String(length=20), nullable=False),
    sa.Column('sanitization_completed_at', sa.DateTime(), nullable=True),
    sa.Column('sanitization_certificate_id', sa.String(length=100), nullable=True),
    sa.Column('quality_control_status', sa.String(length=20), nullable=False),
    sa.Column('final_disposition', sa.String(length=20), nullable=False),
    sa.Column('disposition_reason_code', sa.String(length=50), nullable=True),
    sa.Column('disposition_operator', sa.String(length=100), nullable=True),
    sa.Column('disposition_at', sa.DateTime(), nullable=True),
    sa.Column('resale_listing_id', sa.String(length=36), nullable=True),
    sa.Column('sales_transaction_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['cohort_id'], ['device_cohorts.id'], ),
    sa.ForeignKeyConstraint(['resale_listing_id'], ['resale_listings.id'], ),
    sa.ForeignKeyConstraint(['sales_transaction_id'], ['sales_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_cohort_id'), ['cohort_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_current_status'), ['current_status'], unique=False)

    op.create_table('device_custody_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('custodian', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_custody_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_custody_events_device_id'), ['device_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_custody_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_custody_events_device_id'))

    op.drop_table('device_custody_events')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_current_status'))
        batch_op.drop_index(batch_op.f('ix_devices_cohort_id'))

    op.drop_table('devices')
    # ### end Alembic commands ###
