"""sales discount amount

Revision ID: 0003
Revises: 0002
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_transactions', schema=None) as batch_op:
        batch_op.drop_column('discount_amount')

    # ### end Alembic commands ###
