"use client";
import Link from "next/link";
import { Suspense, useState } from "react";
import { useSearchParams } from "next/navigation";
import DrillPage from "@/components/DrillPage";
import { Card, Chip, Empty, ErrorBox, Loading, PageHeader, SeverityChip, Tabs } from "@/components/ui";
import { cohortHref } from "@/lib/nav";
import { api } from "@/lib/api";
import { useApi } from "@/lib/hooks";
import { dateShort, titleCase } from "@/lib/format";

function Alerts() {
  const [tab, setTab] = useState("open");
  const { data, error, loading, refetch } = useApi<any[]>(tab === "resolved" ? "/api/alerts?status=resolved" : "/api/alerts");
  const [busy, setBusy] = useState<string | null>(null);
  const [draft, setDraft] = useState<Record<string, string>>({});
  const [err, setErr] = useState<string | null>(null);

  const act = async (id: string, action: string, extra: Record<string, unknown> = {}) => {
    setBusy(id); setErr(null);
    try { await api(`/api/alerts/${id}`, { method: "PATCH", body: { action, ...extra } }); setDraft((d) => ({ ...d, [id]: "" })); await refetch(); }
    catch (e: any) { setErr(e.message); } finally { setBusy(null); }
  };
  if (loading) return <Loading />;
  if (error || !data) return <ErrorBox message={error ?? "No data"} onRetry={refetch} />;
  const rows = data.filter((a) => (tab === "critical" ? a.severity === "critical" : true));

  return (
    <>
      <PageHeader title="Action queue" subtitle="What requires action today. Alerts are generated by deterministic rules, tied to a cohort, cell, partner or invoice, and clear themselves when the condition does." />
      <Tabs value={tab} onChange={setTab} tabs={[{ id: "open", label: "Open" }, { id: "critical", label: "Critical only" }, { id: "resolved", label: "Resolved" }]} />
      {err && <div className="mb-3"><ErrorBox message={err} /></div>}
      {rows.length === 0 && <Empty>Nothing here. Quiet is good.</Empty>}
      <div className="space-y-3">
        {rows.map((a) => (
          <Card key={a.id} className={a.severity === "critical" && a.status !== "resolved" ? "border-bad/40" : ""}>
            <div className="flex flex-wrap items-start justify-between gap-3">
              <div className="min-w-0 flex-1">
                <div className="flex flex-wrap items-center gap-2">
                  <SeverityChip severity={a.severity} /><Chip>{titleCase(a.alert_type)}</Chip>
                  {a.status !== "open" && <Chip tone={a.status === "resolved" ? "good" : "info"}>{titleCase(a.status)}{a.status === "snoozed" && a.snoozed_until ? ` until ${dateShort(a.snoozed_until)}` : ""}</Chip>}
                  {a.assigned_to && <Chip tone="info">Owner: {a.assigned_to}</Chip>}
                </div>
                <h2 className="mt-2 text-[15px] font-semibold">{a.title}</h2>
                <p className="mt-0.5 text-sm text-muted">{a.description}</p>
                {a.recommended_action && <p className="mt-2 text-sm"><span className="font-semibold">Recommended: </span>{a.recommended_action}</p>}
              </div>
              {a.cohort_id && <Link className="btn" href={cohortHref(a.cohort_id)}>Open {a.cohort_code}</Link>}
            </div>
            {a.comments.length > 0 && (
              <ul className="mt-3 space-y-1 border-l-2 border-line pl-3 text-xs text-muted">
                {a.comments.slice(-3).map((c: any, i: number) => <li key={i}><b className="text-ink">{c.by}</b> · {c.text}</li>)}
              </ul>
            )}
            {a.status !== "resolved" && (
              <div className="mt-3 flex flex-wrap items-center gap-2">
                <input className="input max-w-xs flex-1" placeholder="Add a comment or owner name…" value={draft[a.id] ?? ""} onChange={(e) => setDraft({ ...draft, [a.id]: e.target.value })} aria-label="Comment or owner" />
                <button className="btn" disabled={busy === a.id || !draft[a.id]} onClick={() => act(a.id, "comment", { text: draft[a.id] })}>Comment</button>
                <button className="btn" disabled={busy === a.id || !draft[a.id]} onClick={() => act(a.id, "assign", { owner: draft[a.id] })}>Assign</button>
                <button className="btn" disabled={busy === a.id} onClick={() => act(a.id, "snooze", { snooze_days: 3 })}>Snooze 3d</button>
                <button className="btn" disabled={busy === a.id || a.status === "escalated"} onClick={() => act(a.id, "escalate")}>Escalate</button>
                <button className="btn btn-primary" disabled={busy === a.id} onClick={() => act(a.id, "resolve", { text: draft[a.id] || undefined })}>Resolve</button>
              </div>
            )}
          </Card>
        ))}
      </div>
    </>
  );
}

/** /alerts?severity=critical&status=open&<dashboard filters> is the "Critical alerts" drill-down; otherwise the action queue. */
function Switch() {
  const sp = useSearchParams();
  return sp.get("severity") || sp.get("status") === "open" ? <DrillPage metric="critical_alerts" /> : <Alerts />;
}

export default function AlertsPage() {
  return <Suspense fallback={<Loading />}><Switch /></Suspense>;
}
